# Generated by Django 6.1 on 2026-08-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
