# Generated by Django 6.1 on 2026-08-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
    ]
