# Generated by Django 6.1 on 2026-09-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_registration_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_picture', models.ImageField(upload_to='bills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
            ],
        ),
    ]
