# Generated by Django 6.1 on 2026-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_code',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_status',
            field=models.CharField(default='yes', max_length=100),
        ),
    ]
