# Generated by Django 6.1 on 2026-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_bill_bill_code_bill_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
